
export const Routes = {
    // pages
    // Presentation: { path: "/" },
    Danang: { path: "/danang" },
    March: { path: "/colours/March" },
    April: { path: "/colours/April" },
    May: { path: "/colours/May" },
    June: { path: "/colours/June" },
    July: { path: "/colours/July" },
    August: { path: "/colours/August" },
    Details: { path: "/detail/Details" },
    Browsers: { path: "/insights/Browsers" },
    Pagenames: { path: "/insights/Pagenames" },
    Countrys: { path: "/insights/Countrys" },
    Devices: { path: "/insights/Devices" },
    Durations: { path: "/insights/Durations" },
    Languages: { path: "/insights/Languages" },
    Pages: { path: "/insights/Pages" },
    Systems: { path: "/insights/Systems" },
    Sizes: { path: "/insights/Sizes" },
    Views: { path: "/insights/Views" },
    DashboardOverview: { path: "/" },
    Transactions: { path: "/transactions" },
    Settings: { path: "/settings" },
    Upgrade: { path: "/upgrade" },
    BootstrapTables: { path: "/tables/bootstrap-tables" },
    CustomReport: { path: "/detail/custom-report" },
    Billing: { path: "/examples/billing" },
    Invoice: { path: "/examples/invoice" },
    Signin: { path: "/examples/sign-in" },
    Signup: { path: "/examples/sign-up" },
    ForgotPassword: { path: "/examples/forgot-password" },
    ResetPassword: { path: "/examples/reset-password" },
    Lock: { path: "/examples/lock" },
    NotFound: { path: "/examples/404" },
    ServerError: { path: "/examples/500" },

};